import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import NameCard from "@/components/NameCard";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        <div className="w-full lg:flex">
          <div className="w-1/3 border hide-on-mobile">
            <NameCard />  
          </div>
          <div className="lg:w-2/3 border">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
