import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import NameCard from "@/components/NameCard";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        <div className="lg:flex lg:m-4">
          <div className="w-1/3 hide-on-mobile">
            <NameCard />  
          </div>
          <div className="lg:w-2/3 lg:mt-16">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}