const Assignments = [
    {
        assignmentId: 1,
        name: "Culminating Task",
        deadline: "2024/08/31 4:00pm EST",
        description: "For your culminating task, you will research a significant event in 20th-century history. You will create a detailed report that includes the causes, key figures, major events, and consequences of the event. Additionally, you will present your findings in a 10-minute presentation to the class. Your report should be at least 1500 words and include at least five credible sources. The presentation should include visual aids such as slides or posters.",
        attachements: "N/A",
        class: "Mrs. Greenaway",
    },
    {
        assignmentId: 2,
        name: "Summative Project",
        deadline: "2024/08/31 4:00pm EST",
        description: "For the summative project, you will work in groups to create a comprehensive project on a topic of your choice related to the course material. This project can take various forms, such as a research paper, a multimedia presentation, or a creative work. Each group must submit a project proposal for approval before proceeding. The final submission should include a written component of at least 2000 words and a presentation to the class.",
        attachements: "N/A",
        class: "Mrs. Greenaway",
    },
    {
        assignmentId: 3,
        name: "Final Exam",
        deadline: "2024/08/31 4:00pm EST",
        description: "The final exam will cover all the material discussed throughout the course. It will consist of multiple-choice questions, short answer questions, and essay questions. You will be tested on your understanding of key concepts, historical events, and their significance. The exam will be conducted in person and will last for 3 hours. Make sure to review all your notes, readings, and previous assignments to prepare thoroughly.",
        attachements: "N/A",
        class: "Mrs. Greenaway",
    },
    {
        assignmentId: 4,
        name: "Culminating Task",
        deadline: "2024/08/31 4:00pm EST",
        description: "For your culminating task, you will research a significant event in 20th-century history. You will create a detailed report that includes the causes, key figures, major events, and consequences of the event. Additionally, you will present your findings in a 10-minute presentation to the class. Your report should be at least 1500 words and include at least five credible sources. The presentation should include visual aids such as slides or posters.",
        attachements: "N/A",
        class: "Mrs. Greenaway",
    },
    {
        assignmentId: 5,
        name: "Summative Project",
        deadline: "2024/08/31 4:00pm EST",
        description: "For the summative project, you will work in groups to create a comprehensive project on a topic of your choice related to the course material. This project can take various forms, such as a research paper, a multimedia presentation, or a creative work. Each group must submit a project proposal for approval before proceeding. The final submission should include a written component of at least 2000 words and a presentation to the class.",
        attachements: "N/A",
        class: "Mrs. Greenaway",
    },
    {
        assignmentId: 6,
        name: "Final Exam",
        deadline: "2024/08/31 4:00pm EST",
        description: "The final exam will cover all the material discussed throughout the course. It will consist of multiple-choice questions, short answer questions, and essay questions. You will be tested on your understanding of key concepts, historical events, and their significance. The exam will be conducted in person and will last for 3 hours. Make sure to review all your notes, readings, and previous assignments to prepare thoroughly.",
        attachements: "N/A",
        class: "Mrs. Greenaway",
    },
    {
        assignmentId: 7,
        name: "Culminating Task",
        deadline: "2024/08/31 4:00pm EST",
        description: "For your culminating task, you will research a significant event in 20th-century history. You will create a detailed report that includes the causes, key figures, major events, and consequences of the event. Additionally, you will present your findings in a 10-minute presentation to the class. Your report should be at least 1500 words and include at least five credible sources. The presentation should include visual aids such as slides or posters.",
        attachements: "N/A",
        class: "Mrs. Greenaway",
    },
    {
        assignmentId: 8,
        name: "Summative Project",
        deadline: "2024/08/31 4:00pm EST",
        description: "For the summative project, you will work in groups to create a comprehensive project on a topic of your choice related to the course material. This project can take various forms, such as a research paper, a multimedia presentation, or a creative work. Each group must submit a project proposal for approval before proceeding. The final submission should include a written component of at least 2000 words and a presentation to the class.",
        attachements: "N/A",
        class: "Mrs. Greenaway",
    },
    {
        assignmentId: 9,
        name: "Final Exam",
        deadline: "2024/08/31 4:00pm EST",
        description: "The final exam will cover all the material discussed throughout the course. It will consist of multiple-choice questions, short answer questions, and essay questions. You will be tested on your understanding of key concepts, historical events, and their significance. The exam will be conducted in person and will last for 3 hours. Make sure to review all your notes, readings, and previous assignments to prepare thoroughly.",
        attachements: "N/A",
        class: "Mrs. Greenaway",
    },
]

export default Assignments